Update README.md
running the original `pip install .` threw the following error due to directory issues:

```bash
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```

The following change bypassed the wd issue and worked: 

```bash
pip install gp
```

Thus, I am suggesting this change.